version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/kursy
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    command: npm run serve # Uruchamia Vue.js w trybie developerskim
    ports:
      - "8080:8080"
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
